inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

Lint/RedundantDirGlobSort:
  Exclude:
    - 'spec/rails_helper.rb'

Rails/I18nLocaleAssignment:
  Enabled: false
